apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bullmq
    app.kubernetes.io/managed-by: Helm
  name: bullmq
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: bullmq
  type: NodePort
status:
  loadBalancer: {}
